version: '3.5'

services:
  boatmanapi:
    image: ${DOCKER_REGISTRY-}boatmanapi
    build:
      context: .
      dockerfile: backend/src/Boatman.WebHost/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ConnectionStrings:DomainConnection=Host=localhost;Port=5432;Database=Boatman.DomainDb;Password=@Super(!)StrongPwd
     - ConnectionStrings:IdentityConnection=Host=localhost;Port=5432;Database=Boatman.IdentityConnectionDb;Password=@Super(!)StrongPwd
    ports:
    - "5120:8080"
    depends_on:
      - "postgresql"
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=@Super(!)StrongPwd