version: '3.5'

services:
  boatmanapi:
    image: ${DOCKER_REGISTRY-}boatmanapi
    build:
      context: ./backend
      dockerfile: src/Boatman.WebHost/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ConnectionStrings:DomainConnection=Host=domaindb;Port=5432;Database=Boatman.DomainDb;User Id=postgres;Password=@Super(!)StrongPwd
     - ConnectionStrings:IdentityConnection=Host=identitydb;Port=5432;Database=Boatman.IdentityDb;User Id=postgres;Password=@Super(!)StrongPwd
    ports:
    - "5120:8080"
    depends_on:
      - "domaindb"
      - "identitydb"
  domaindb:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=Boatman.DomainDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Super(!)StrongPwd
  identitydb:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=Boatman.IdentityDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Super(!)StrongPwd
