version: '3.5'

services:
  boatmanapi:
    image: ${DOCKER_REGISTRY-}boatmanapi
    build:
      context: ./backend
      dockerfile: src/Boatman.WebHost/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ConnectionStrings:DomainConnection=Host=postgresql;Port=5430;Database=Boatman.DomainDb;Password=@Super(!)StrongPwd
     - ConnectionStrings:IdentityConnection=Host=postgresql;Port=5430;Database=Boatman.IdentityDb;Password=@Super(!)StrongPwd
    ports:
    - "5120:8080"
    depends_on:
      - "postgresql"
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Super(!)StrongPwd
