name: CI

on:
  [ push, pull_request ]

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AwsCredentials:AwsSecretKey: ${{ secrets.AWS_CREDENTIALS__AWS_SECRET_KEY }}
      AwsCredentials:AwsKey: ${{ secrets.AWS_CREDENTIALS__AWS_KEY }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
