name: CI

on:
  [ push, pull_request ]

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      env:
          AwsCredentials__AwsKey: ${{ secrets.AWSCREDENTIALS__AWSKEY }}
          AwsCredentials__AwsSecretKey: ${{ secrets.AWSCREDENTIALS__AWSSECRETKEY }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
