# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  [ push ]

defaults:
run:
  shell: bash
  working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup .NET
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
